{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dropdeck-app.serviceAccountName" . }}
  labels:
{{ include "dropdeck-app.labels" . | nindent 4 }}
{{- end -}}
