# Dropdeck deployment configuration

ingress:
  ipName: preview-cluster-ip
  host: app.dropdeck.com
  metadata:
    annotations:
      kubernetes.io/ingress.global-static-ip-name: preview-static
      # networking.gke.io/managed-certificates: dropdeck-cert

nameOverride: ""
fullnameOverride: ""

dropdeck-export-api:
  image:
    tag: preview # default image tag

  log:
    level: debug

  cors:
    allowedOrigins: '*,https://login.live.com,https://login.microsoftonline.com'

  frontend:
    host: https://app.dropdeck.com
    player:
      host: https://deck.show
    export:
      host: https://app.dropdeck.com
      path: export/play

  backend:
    host: https://app.dropdeck.com/api

  storage:
    cloud:
      google:
        bucketName: dropdeck-files_preview
        enabled: true
    disk:
      path: /data

  auth:
    allowed:
      users: ^bjarki.holm@gmail.com$,^mr.olafsson@gmail.com$,^theobonhamcarter@gmail.com$
      organizations: ^dropdeck.com$,^harvey-medical.com$
    google:
      clientId: 475661889060-nmt1nnj2tde71878c4k471ess91gacnm.apps.googleusercontent.com
      secret: RNXLWAzpbQEB3Yq2-idLHjFf
    o365:
      clientId: b3ab1206-c54c-4194-92a4-222c89b2074c
      secret: 5o6ifAVNS-~TJW~g8_aFoHq7c9.d.BD5-_

  mongodb:
    enabled: false # Now connecting to MongoDB Atlas

  services:
    browserless:
      apiToken: d79d40eb-cfd5-41a7-83f5-68b0f725880a
      enabled: true
      url: wss://chrome-eu-uk.browserless.io # ws://dropdeck-chrome:3000
      dataDir: /tmp/dropdeck-cache
    unsplash:
      accessKey: 909c3b1e2791705c0208a7f4616aebe5625f4449763d1c3d47293b93b1278645
      secretKey: e739ce3f12aba801389d20e96549951851a20d7f310fac766009bf98b9269411
    brandfetch:
      accessKey: VNyHYLiTPn6feMCNQrR2J7Ko5G4AUmyq5vPdBJG2
    giphy:
      accessKey: 0lmqv7AWPWtbfsxMfnuWcOkd3K5R9R91

  helmet:
    rateLimit:
      max: 100 # max number of requests during a sliding window
      window: 5 # rate limit window, in minutes

  routes:
    export: true # ENABLE the export API

dropdeck-app:
  image:
    tag: preview # default image tag
  analytics:
    fullStory: disabled

dropdeck-app-server:
  log:
    level: trace
  api:
    host: https://app.dropdeck.com/api
  app:
    player:
      host: https://deck.show
      embed:
        host: https://app.dropdeck.com/play

dropdeck-api:
  image:
    tag: preview # default image tag

## From k8s secret mongodb-atlas-secret
#  database:
#    host: ...
#    user: ...
#    password: ...
#    initdb: ...

  log:
    level: info

  cors:
    allowedOrigins: '*,https://login.live.com,https://login.microsoftonline.com'

  frontend:
    host: https://app.dropdeck.com
    player:
      host: https://deck.show

  backend:
    host: https://app.dropdeck.com/api

  storage:
    cloud:
      google:
        bucketName: dropdeck-files_preview
        enabled: true
    disk:
      path: /data

  auth:
    allowed:
      users: ^bjarki.holm@gmail.com$,^mr.olafsson@gmail.com$,^theobonhamcarter@gmail.com$
      organizations: ^dropdeck.com$,^harvey-medical.com$
    google:
      clientId: 475661889060-nmt1nnj2tde71878c4k471ess91gacnm.apps.googleusercontent.com
      secret: RNXLWAzpbQEB3Yq2-idLHjFf
    o365:
      clientId: b3ab1206-c54c-4194-92a4-222c89b2074c
      secret: -NUMw0IyO1onBfT1..9fh7rzspV.K8h4fh


  mongodb:
    enabled: false # Now connecting to MongoDB Atlas

  services:
    unsplash:
      accessKey: 909c3b1e2791705c0208a7f4616aebe5625f4449763d1c3d47293b93b1278645
      secretKey: e739ce3f12aba801389d20e96549951851a20d7f310fac766009bf98b9269411
    brandfetch:
      accessKey: VNyHYLiTPn6feMCNQrR2J7Ko5G4AUmyq5vPdBJG2
    giphy:
      accessKey: 0lmqv7AWPWtbfsxMfnuWcOkd3K5R9R91

  helmet:
    rateLimit:
      max: 100 # max number of requests during a sliding window
      window: 5 # rate limit window, in minutes

  routes:
    export: false # DISABLE the export API
