version: "2"
services:

#    app:
#        container_name: dropdeck-app
#        build:
#            context: ./app
#            dockerfile: deployment/docker/Dockerfile.dev
#        restart: always
#        env_file: .env.development
#        ports:
#            - "3000:3000"
#        volumes:
#            - ./app:/app
#            - /app/node_modules
#        links:
#            - api
#        networks:
#            - dropdeck-network

    api:
        container_name: dropdeck-api
        build:
            context: .
            dockerfile: services/api/deployment/docker/dev/Dockerfile
        image: dropdeck-api:dev
        restart: always
        env_file: .env.development
        ports:
            - "9000:9000"
        volumes:
            - ./services/api/src:/usr/src/dropdeck/services/api/src
#            - /node_modules
#            - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/keys/gcp-credentials.json:ro
        depends_on:
            - db
        networks:
            - dropdeck-network
    db:
        container_name: dropdeck-db
        image: mongo
        restart: unless-stopped
        env_file: .env.development
        volumes:
            - ./services/api/deployment/helm/dropdeck-api/charts/mongodb/files/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
            - ./data:/data/db
        ports:
            - 27017:27017
        networks:
            - dropdeck-network
networks:
    dropdeck-network:
        driver: bridge
