apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dropdeck-export-app.fullname" . }}
  labels:
    {{- include "dropdeck-export-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dropdeck-export-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dropdeck-export-app.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dropdeck-export-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

           # TODO: Define reasonable liveness and readiness probes
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:

            # Override default API host
            - name: REACT_APP_API_HOST
              value: "{{ .Values.api.host }}"

            # Enable Export Player view
            - name: REACT_APP_MODULES_EXPORT_PLAYER
              value: "true"

            # Disable analytics for headless app
            - name: REACT_APP_FULLSTORY
              value: "disabled"
            - name: REACT_APP_GOOGLE_ANALYTICS
              value: "disabled"

    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
