apiVersion: v1
kind: Service
metadata:
  name: {{ include "dropdeck-api.fullname" . }}
  labels:
    {{- include "dropdeck-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} # http
      protocol: TCP
      name: http
  selector:
    {{- include "dropdeck-api.selectorLabels" . | nindent 4 }}
